const fs = require('fs');

const traitsMap = {
    esPlanta: { p: 3143, e: '🌿', texts: ['¿Está sujeto al suelo y tiene hojas (planta)?', '¿Es un organismo sésil fijado al suelo (planta)?', '¿Es un organismo autótrofo sésil (Reino Plantae)?'] },
    esArbolAlto: { p: 2256, e: '🌳', texts: ['¿Tiene un solo tronco duro de madera marrón (árbol)?', '¿Posee un tronco central leñoso (árbol)?', '¿Presenta biotipo arbóreo con tronco leñoso principal?'] },
    esTrepadora: { p: 3143, e: '🧗', texts: ['¿Crece trepando o enrollándose por otras superficies?', '¿Presenta tallos trepadores que se apoyan en otras estructuras?', '¿Es una planta de hábito escandente o trepador?'] },
    tienePinchos: { p: 39007, e: '🌵', texts: ['¿Tiene pinchos o espinas duras?', '¿Posee formaciones punzantes o espinas?', '¿Presenta estructuras defensivas lignificadas (espinas)?'] },
    esAromatica: { p: 3102, e: '👃', texts: ['¿Desprende un olor fuerte al frotar sus hojas?', '¿Exhala un aroma intenso al frotar alguna de sus partes?', '¿Secreto compuestos volátiles aromáticos perceptibles?'] },
    esPequenaSuelo: { p: 3113, e: '🌱', texts: ['¿Crece pegada al suelo midiendo menos de 10 cm?', '¿Es una planta de porte rastrero menor a 10 cm?', '¿Es una especie herbácea rastrera de escasa altura?'] },
    hojaAguja: { p: 2256, e: '🌲', texts: ['¿Tienen sus hojas forma de aguja fina?', '¿Presenta hojas muy estrechas y alargadas (forma de aguja)?', '¿Desarrolla hojas aciculares?'] },
    daPinones: { p: 2256, e: '🌰', texts: ['¿Da piñas duras que contienen semillas llamadas piñones?', '¿Produce conos grandes que albergan semillas (piñones)?', '¿Desarrolla estróbilos ovoides con grandes semillas comestibles?'] },
    daHigos: { p: 2256, e: '🍐', texts: ['¿Produce frutos blandos llamados higos?', '¿Desarrolla frutos carnosos conocidos como higos?', '¿Produce infrutescencias denominadas siconos (higos)?'] },
    daAlmendras: { p: 2256, e: '🥜', texts: ['¿Su semilla está dentro de una cáscara dura?', '¿Produce un fruto con dura envuelta protegiendo la semilla?', '¿Desarrolla drupas con endocarpio leñoso surcado?'] },
    daBellotas: { p: 2256, e: '🌰', texts: ['¿Su fruto tiene un "sombrerito" rugoso (bellota)?', '¿Produce bellotas cubiertas parcialmente por una cúpula?', '¿Desarrolla aquenios encajados en cúpula escamosa (bellota)?'] },
    hojaLobulada: { p: 2256, e: '🍂', texts: ['¿El borde de su hoja tiene curvas profundas (lóbulos)?', '¿El margen de la hoja presenta curvas pronunciadas?', '¿Posee lámina foliar profundamente pinnatilobada o sinuada?'] },
    maderaBlancaAgua: { p: 2256, e: '💧', texts: ['¿Tiene la corteza gris pálida y crece junto al agua?', '¿Presenta corteza clara y es propia de zonas de agua?', '¿Posee corteza lisa blanca y es típica de bosque de galería?'] },
    hojasAsimetricas: { p: 2256, e: '🍃', texts: ['¿La base de su hoja es más larga de un lado que del otro?', '¿La base de la hoja es claramente asimétrica?', '¿Presenta lámina foliar con asimetría basal evidente?'] },
    bayasMermelada: { p: 30241, e: '🫐', texts: ['¿Produce ramilletes muy juntos de bolitas oscuras (bayas)?', '¿Da infrutescencias formadas por diminutas bayas oscuras?', '¿Desarrolla densos corimbos de pequeñas drupas violáceas?'] },
    florTuboDulce: { p: 3102, e: '🌸', texts: ['¿Sus flores tienen forma de tubo alargado?', '¿Tienen sus flores forma tubular estrecha?', '¿Presenta corolas marcadamente tubulares zigomorfas?'] },
    florVisteria: { p: 3102, e: '🌹', texts: ['¿Sus flores tienen muchas capas de pétalos (rosas)?', '¿Sus flores disponen de numerosos pétalos solapados?', '¿Manifiesta flores con estambres hipertrofiados petaloideos?'] },
    daMoras: { p: 30241, e: '🫐', texts: ['¿Da frutos formados por bolitas agrupadas (moras)?', '¿Produce frutos compuestos por pequeñas esferitas?', '¿Desarrolla infrutescencias de tipo eterio con drupéolas negras?'] },
    espinasLargasCardo: { p: 39007, e: '🦔', texts: ['¿Su flor es redonda, seca y de color morado (cardo)?', '¿Remata su tallo espinoso en una cabezuela floral morada?', '¿Presenta prominentes capítulos flosculosos púrpuras con brácteas duras?'] },
    hueleMenta: { p: 3143, e: '🌿', texts: ['¿Huele de forma muy parecida al chicle de menta?', '¿Desprende intenso olor mentolado al frotar sus hojas?', '¿Exuda altos niveles de aceites esenciales ricos en mentol?'] },
    florMoradaEspigaJabon: { p: 3102, e: '🪻', texts: ['¿Sus pequeñas flores moradas forman grupitos en vertical (espiga)?', '¿Las flores moradas se agrupan en estrechas espigas altas?', '¿Muestra densas espigas verticiladas de corolas purpúreas?'] },
    hojasHilosAnis: { p: 3143, e: '🌱', texts: ['¿Sus hojas parecen cabellos verdes muy finos y huelen a anís?', '¿Posee hojas extremadamente finas con olor anisado?', '¿Presenta frondes multi-pinnatisectas finísimas ricas en anetol?'] },
    florManzanilla: { p: 3102, e: '🌼', texts: ['¿Da flores menores de 2 cm parecidas a margaritas?', '¿Produce diminutas flores tipo margarita de botón amarillo?', '¿Genera reducidos capítulos estradiados con flósculos amarillos?'] },
    cocinarCarne: { p: 3143, e: '🥩', texts: ['¿Sus hojas parecen agujas y huelen muy bien (romero)?', '¿Son sus hojas lineares duras con el envés muy blanco?', '¿Desarrolla denso follaje esclerófilo con tricomas glandulares alifáticos?'] },
    tomilloCaracteristico: { p: 3143, e: '🌿', texts: ['¿Sus hojas miden menos de medio centímetro agrupadas?', '¿Tiene hojas minúsculas (menores a 5 mm) en matas densas?', '¿Es un subcaméfito densamente foliado por hojas simples menores a 5mm?'] },
    alfombraPiedras: { p: 3113, e: '🧽', texts: ['¿Crece pegado a rocas o troncos sin tener grandes raíces?', '¿Forma tapices sobre piedras o superficies sin generar troncos?', '¿Trátase de briófitos formadores de densos tapices sobre sustrato duro?'] },
    hojaCorazon: { p: 3143, e: '🍀', texts: ['¿Cada de sus hojas está formada por 3 o 4 piececitas en forma de corazón?', '¿La hoja principal se divide en 3 foliolos en forma de corazón?', '¿Muestra hojas característicamente trifoliadas con foliolos obcordados?'] },
    hojaFronde: { p: 3143, e: '🌿', texts: ['¿Sus hojas nuevas nacen enrolladas en forma de espiral?', '¿Las primeras hojas de los brotes se desarrollan enrolladas?', '¿Presenta característica vernación circinada en el desarrollo de frondes jóvenes?'] },
    picaPiel: { p: 39007, e: '🔥', texts: ['¿Rozar sus hojas produce mucho picor u orticaria?', '¿Causa escozor rápido e inflamación cutánea si la tocas?', '¿Posee numerosos tricomas urticantes secretores de histamina exógena epidérmica?'] },
    pareceOrtigaBlanca: { p: 3102, e: '🤍', texts: ['¿Tiene flores blancas pequeñas y su contacto NO causa picor?', '¿Desarrolla flores blancas de dos "labios", careciendo totalmente de pelos urticantes?', '¿Trátase de dicotiledóneas inermes y de destacadas corolas bilabiadas blanquecinas?'] },
    florRojaPapel: { p: 3102, e: '🌺', texts: ['¿Su única flor tiene 4 pétalos rojos arrugados muy finos?', '¿Posee llamativas flores solitarias de 4 pétalos rojos frágiles?', '¿Desarrolla flores tetrámeras de pétalos papiráceos efímeros pigmentados de rojo?'] },
    semillaAbuelo: { p: 3102, e: '🌬️', texts: ['¿Sus semillas forman un globo de pelitos blancos (abuelo)?', '¿Desarrolla una esfera volátil completa de finos pelos blancos al semillar?', '¿Los aquenios desarrollan extensos vilanos plumosos dispersos anemocoramente en globo?'] },
    florMargarita: { p: 3102, e: '🌼', texts: ['¿Su flor mide más de 2 cm con el centro todo amarillo y pétalos blancos?', '¿Da flores clásicas mayores de 2 cm tipo margarita de extenso disco central?', '¿Exhiba cabezuelas capítulos radiados superiores a 20 mm con lígulas blancas evidentes?'] },
    florAzulCeleste: { p: 3102, e: '💠', texts: ['¿Tiene flores de un color azul clarito vivo o cielo vivo?', '¿Emite flores de forma deshilachada y brillante color azul celeste?', '¿Elabora notables cabezuelas inflorescencias con presencia de lígulas cromáticas azul-cielo?'] },
    florAmarillaSinHojas: { p: 30241, e: '💛', texts: ['¿Sus tallos verdes apenas tienen hojas y crecen como palos delgados?', '¿Es un matorral espeso con largas varas cilíndricas verdes casi carentes de hojas?', '¿Biotipo consistente principalmente en brotes caulinares asimiladores de clorofila y hojas mermadas?'] },
    hojasPringosas: { p: 3143, e: '🍯', texts: ['¿Tocar sus oscuras hojas te deja una sensación muy pegajosa (pringosa)?', '¿Exuda en gran abundancia una densa y perceptible capa de resina pegajosa foliar?', '¿La epidermis presenta copiosa excreción resino-mucilaginosa de adherencia activa pronunciada?'] },
    florRosaMoradaAbanico: { p: 3102, e: '🌸', texts: ['¿Tiene hoja con bordes arrugados redondos parecida a un abanico verde?', '¿Ostenta láminas foliares achatadas redondas, similar a un abanico plegado?', '¿Sus hojas poseen una morfología típicamente reniforme-orbicular o abiertamente palmatilobada?'] },
    florVioletaRacimo: { p: 3102, e: '💜', texts: ['¿Las flores violetas tienen distintos tamaños en sus 5 pétalos?', '¿Florece con pequeñas corolas irregulares de matiz violáceo y forma despareja?', '¿Desarrolla estructuralismo de corolas netamente zigomorfas, dotadas típicamente de espolones lila?'] },
    hojaAnchaNervios: { p: 3143, e: '🍃', texts: ['¿La hoja sale a ras del suelo y tiene rayas paralelas de base a punta muy gruesas?', '¿Sus hojas bajas achatadas exhiben gruesos y numerosos nervios rectos longitudinales prominentes?', '¿Trátase de un fenotipo herbáceo acaule provisto fuertemente de patentes venaciones paralelinervias?'] },
    tieneHuesos: { p: 24913, e: '🦴', texts: ['¿Tiene huesos dentro de su cuerpo (Vertebrado)?', '¿Posee un esqueleto óseo interno a lo largo de su cuerpo?', '¿Se caracteriza anatómicamente por la presencia de neurocráneo y columna vertebral endoesquelética?'] },
    vuela: { p: 6246, e: '✈️', texts: ['¿Tiene alas completamente capaces de elevarlo y mantener vuelo por el aire?', '¿Resultan sus alas un par de apéndices funcionales para sostenerse en vuelo libre aéreo continuado?', '¿Manifiesta prolongaciones orgánicas inervadas eficientes que posibilitan locomoción aerodinámica?'] },
    tienePatas: { p: 8666, e: '🐾', texts: ['¿Tiene extremidades para caminar ("patas")?', '¿Cuenta con el cuerpo dotado de extremidades articuladas especializadas en marchar?', '¿Exhibe apéndices tegumentarios articulados anatómicamente modificados hacia su tracción terrestre (patas)?'] },
    muchasPatas: { p: 8666, e: '🐛', texts: ['¿Tiene sumando un total de más de 8 patas?', '¿En su cuerpo segmentado, pueden distinguirse o contar una sumatoria que supera las 8 patas?', '¿El metamerismo de su anatomía origina y soporta más de una cuartena de pares locomotores (>8 patas)?'] },
    ochoPatas: { p: 8666, e: '🕷️', texts: ['¿Tiene exactamente 8 extremidades para caminar (Cuerpo en dos partes)?', '¿Presenta el recuento exacto y contable de 8 patas locomotoras (Arácnido)?', '¿Fórmula apendicular estricta consistente en tenencia morfoestructural de 4 pares idénticos de patas funcionales?'] },
    seisPatas: { p: 8666, e: '🐜', texts: ['¿Tiene el recuento total y exacto a 6 patas para andar (Insecto normal)?', '¿Contabiliza estrictamente tres pares de extremidades articuladas o 6 patas en total?', '¿Sigue la organización corporal hexápoda obligada taxonómicamente a 3 pares completos para desplazamiento?'] },
    alasMuyGrandesBonitas: { p: 6246, e: '🦋', texts: ['¿Sus enormes alas tapadas en escamas de variados colores opacan su cuerpo (mariposa)?', '¿Revolotea mediante grandes alas oscurecidas por tupido polvo colorizado vistosos?', '¿Posee gran envergadura tegminal tapizada estructuralmente de abigarradas microscópicas escamas desprendibles?'] },
    blanca: { p: 5406, e: '⚪', texts: ['¿Es casi todo de color blanco?', '¿Su coloración general dominante es totalmente blanca, careciendo de marcas extensas?', '¿Fenotipo estético corporal manifestando uniformidad cromática albinoluminosa sin alteraciones extremas?'] },
    amarilla: { p: 5406, e: '🟡', texts: ['¿Destaca a simple vista por ser de color amarillo brillante?', '¿Sobresalen y dominan las partes altas de sus formas la coloración amarillenta viva?', '¿Exhibición extendida fuertemente xántica pigmentaria del exoesqueleto del lepidóptero?'] },
    saleNoche: { p: 37028, e: '🌙', texts: ['¿Suele esconderse de día y volar aturdida por la noche (Polilla)?', '¿Su principal actividad es siempre tras el atardecer volando por la noche?', '¿Manifiesta un hábito puramente crepuscular o nocturno viéndose atraída fuertemente a las luminarias estivales?'] },
    comeRopa: { p: 3143, e: '👕', texts: ['¿Mide solo 1 cm y es lisa color crema y come tela (Polilla doméstica en ropa)?', '¿Minúscula polilla amarillenta o beige de 1 cm, oculta estropeando tejidos oscuros o cerrados?', '¿Microlepidóptero Tineidae de modesto centímetro, pardeado uniforme pálido sinántrópico marcadamente fibrifagia?'] },
    haceMiel: { p: 31403, e: '🐝', texts: ['¿Tiene su gordito cuerpo pardo recubierto de muchos pelitos amarrillentos (Abeja que hace miel)?', '¿Pilosísima corpulenta oscura encargada de recolectar polen para las colmenas?', '¿Apis mellifera, fuertemente setosa sobre marrón cobrizo o dorada empleada a apicultura colectiva himenóptera?'] },
    rayasAvispa: { p: 5406, e: '🐝', texts: ['¿Su cuerpo picudo brillante y liso pelado mezcla rayas amarillas y franjas negras (Avispa)?', '¿Posee el abdomen brillante "pelado", con contrastantes franjas horizontales de peligro amarillas y negras?', '¿El gáster glabro resplandece exhibiendo claro aposematismo compuesto a fascías maculadas melánicas y gualdas sulfuradas?'] },
    nidoBarro: { p: 6978, e: '🏺', texts: ['¿Es una abeja-avispa muy grande, con la cintura súper fina como un hilo largo negro (Avispa Alfarera)?', '¿Voluptuosa y oscura avispón, caracterizada enormemente por su estrechísima y larguísima cintura pedunculada inerme de nidos?', '¿Esfécido de inconfundible vuelo grave dominado un esclerotizado pedicelo abdominal filiforme que prolonga o aleja en gran lomo el gáster macizo uropodonal?'] },
    chupaSangrePita: { p: 7281, e: '🦟', texts: ['¿Es minúsculo, parece de frágiles largas patas y pica chupando sangre emitiendo chirrido agudo zumbante?', '¿Sutil mosquitillo percutidor zumbante que te pica en silencio tras buscarte en vuelo a la noche?', '¿Díptero culícido nematócero fino de probóscide perforante-succionadora, patas extremadamente filiformes y silvido intermitente audíble nocturno de vuelo?'] },
    cuerpoHelicopteroCazaAgua: { p: 6246, e: '🚁', texts: ['¿Su cuerpo largo verde o azul vuela brillando sobre los charcos en línea recta de helicóptero (Libélula)?', '¿Grandioso cilindro de cuatro alas quietamente hialinas sobre corrientes y un abdomen tan largo como sus alas juntas?', '¿Odonato ágil o zigóptero de estilización prolongada cilíndrica a pterotórax inalterado provisto de robustas dobles alas no replegables refulgidoras sobre humedales?'] },
    cantaVerano: { p: 37028, e: '🎶', texts: ['¿En pleno día verano hace y canta de forma muy ruidosa larguísimo canturro siseo en los arbolitos (Cigarra / Chicharra)?', '¿Estricta estriduladora diurna que canta ensordecedoramente fuerte en el verano aferrada en las ramas secas al calor estival?', '¿Gran insecto del tipo cigárido que monopoliza coros acústicos estivales estridentes gracias a tímpanos u siringes especializadas ventrales del torax asimiladoras homópticas?'] },
    verdeMetalicoAcudeCaca: { p: 5406, e: '💩', texts: ['¿Mosca grande y gruesa que siempre tiene un color de metal como oro brilloso verde vivo sobre caca?', '¿Es un moscardón inconfundible en tamaño y robustez, tintado completamente por brillos verde esmeralda y metal azul acudiendo asqueroso y necrófago?', '¿Calliforido necrófago o coprófago (Lucilia sp. - moscardas verdes) manifestando intenso brillo tornasolado estructural de verde cromo o cian metálico iridiscente no piloso en tórax y tergitos?'] },
    conchaEspiral: { p: 25016, e: '🐌', texts: ['¿El animal blando transporta sobre él la concha de calcio dura siempre enrollada circular?', '¿Posee un evidente caparazón externo calcáreo que crece girando en marcada espiral?', '¿Es un molusco gasterópodo provisto de concha helicoidal opaca calcificada?'] },
    rastroBaba: { p: 2360, e: '💧', texts: ['¿Es como un caracol liso blando pero sin llevar concha (Babosa)?', '¿Es una babosa desnuda de aspecto carnoso asimétrico que segrega brillante moco al deslizar?', '¿Gasterópodo pulmonado nudo, exento de formación conquiológica visible externa exhibiendo manto húmedo?'] },
    seHaceBolita: { p: 7498, e: '🪨', texts: ['¿Es capaz de hacerse una bolita redondita, como una canica gris, si lo tocas?', '¿Crustáceo gris de la humedad capaz de enrollarse formando una esfera perfecta defensiva?', '¿Crustáceo isópodo terrestre provisto de conglobación plástica (enrollamiento) a esfera estricta?'] },
    correRapidoPinzas: { p: 34835, e: '🗡️', texts: ['¿Va rápido por el suelo, es largo y plano, y tiene pinzas venenosas en la cabeza (Escolopendra o Ciempiés)?', '¿Miriápodo ágil plano dorsiventralmente asustadizo a rápida marcha oculto bajo rocas, con picos inyectores frontales?', '¿Quilópodo miriápodo plano dorsiventralmente lucífugo destacando un metaméro maxilípedo con forcípulas venenosas frontales?'] },
    parasitoSangre: { p: 7281, e: '🧛', texts: ['¿Es como una lentejita gorda que chupa la sangre agarrada a la piel de los perros (Garrapata)?', '¿Ácaro parásito chupasangres aferrado a la piel de animales domésticos engordando inmensa forma en bola por sangre fresca?', '¿Ácaro hematófago e ixódido de idiosoma nudo altamente elongable ante ingestas masivas de succión eritrocitaria?'] },
    telaranaCruz: { p: 25600, e: '🕸️', texts: ['¿Es grande, marrón amarillento, hace telas de araña y tiene una cruz blanca dibujada en la espalda?', '¿Gran Araña vistosa tejedora en exterior con un ancho vientre marcado por evidente motivo de cruz pálida?', '¿Arácnido araneiforme tejedor orbicular prominente asumiendo enorme gáster ornamentado con maculación en leuco-cruz?'] },
    patasTraserasSaltarinas: { p: 8666, e: '🦘', texts: ['¿Tiene las dos patas traseras gigantes y dobladas para dar grandísimos saltos (Saltamonte)?', '¿Destaca un par trasero de patas gigantescas e hiper musculadas preparadísimas al largo brinco propulsor?', '¿De las 6 de patas del ortóptero, sus dos posteriores metatorácicas sufren hipertrófico engrose musculado femoral de resorte?'] },
    cantaNocheOscuro: { p: 37028, e: '🦗', texts: ['¿Bicho gordo negro que canta chirri chillante "cri... cri.." desde escondites de noche en el jardín (Grillo)?', '¿Insecto oscuro de alas duras que canta de noche un chirrido constante sin parar machuno corto (Grillo)?', '¿Ortóptero de coloración oscura que estridula intensamente durante la etapa nocturnal emitiendo un continuo cri-cri?'] },
    pulgaChupaSangre: { p: 7281, e: '🩸', texts: ['¿Es minúscula, rojiza y da saltos gigantes en el pelo de los perros chupando sangre (Pulga)?', '¿Diminuto hiper-saltador muy molesto que infesta matorrales o pelaje animal chupando sangre veloz pulga?', '¿Parásito áptero muy estidigitado achatado lateralmente que efectúa asombrosos largos saltos cinéticos?'] },
    verdeHierbaAlta: { p: 5406, e: '🦗', texts: ['¿Es como un palito largo saltador, verde por completo, camuflado en la hierba?', '¿Grácil insecto o saltamontes color verde brillante hierba alargado, camuflado largo de fito verde hierbal?', '¿Ensifero grácil mimético, color verde críptico isocrómico largo con la vegetación herbácea circundante?'] },
    caparazonDuroDorso: { p: 25016, e: '🛡️', texts: ['¿Sus alas superiores son duras y rígidas como un caparazón protector en la espalda (Escarabajos y mariquitas)?', '¿Las alas exteriores delanteras son esclerotizadas durísimas funcionando como un escudo brillante en la espalda?', '¿Exhiben alas anteriores altamente endurecidas y esclerotizadas formando élitros coriáceos protectores a modo escudo?'] },

    // ==========================================
    // VERTEBRADOS (HUESOS)
    // ==========================================
    tienePlumasPico: { p: 6248, e: '🪶', texts: ['¿Tiene el cuerpo cubierto de plumas y la boca es un pico duro (Ave)?', '¿Su cuerpo está cubierto de plumas y presenta un pico córneo?', '¿Posee un cuerpo cubierto de plumas y mandíbulas revestidas por un rhamphotheca (pico córneo)?'] },
    tienePelo: { p: 7281, e: '🐻', texts: ['¿Tiene el cuerpo cubierto de pelo (Mamífero)?', '¿Su cuerpo está recubierto parcialmente de pelo?', '¿Presenta el cuerpo total o parcialmente recubierto de folículos pilosos?'] },
    tiene4Patas: { p: 8666, e: '🦎', texts: ['¿Tiene cuatro patas para caminar o saltar?', '¿Es un tetrápodo con cuatro extremidades marchadoras?', '¿Posee cuatro extremidades quiridias funcionales para locomoción terrestre?'] },

    // AVES
    gorrionRechoncho: { p: 6246, e: '🐦', texts: ['¿Es un pajarito pequeño y regordete de color marrón que salta por el suelo ("Gorrión")?', '¿Pequeña ave paseriforme de plumaje pardo muy común en las ciudades?', '¿Paseriforme urbano de pequeño tamaño, aspecto robusto y plumaje críptico parduzco?'] },
    palomaCiudad: { p: 6246, e: '🕊️', texts: ['¿Mide casi dos palmos y suele ser gris (Paloma)?', '¿Ave grisácea de tamaño mediano que camina moviendo la cabeza?', '¿Columbiforme de tamaño medio, predominantemente gris o azulado, de caminar característico?'] },
    tortolaCollar: { p: 6246, e: '🕊️', texts: ['¿Es como una paloma fina de color arena clara con una "bufanda" o rayita negra en el cuello (Tórtola)?', '¿Columbiforme color canela claro con una distintiva marca negra en el cuello?', '¿Columbídeo de coloración isabelina con un collar nucal melánico distintivo?'] },
    urracaRobabrillos: { p: 6246, e: '🐧', texts: ['¿Es grande, de colores blanco y negro, con la cola muy larga (Urraca)?', '¿Córvido grande de plumaje blanco y negro brillante con extensa cola?', '¿Córvido de notable envergadura, plumaje pío (blanco y negro irisado) y plumas caudales elongadas?'] },
    cuervoNegro: { p: 6246, e: '🐦‍⬛', texts: ['¿Es un pájaro grande y completamente negro por todas partes (Cuervo)?', '¿Gran córvido de plumaje enteramente negro brillante?', '¿Córvido de gran tamaño y plumaje uniformemente melánico con irisaciones metálicas?'] },
    mirloPicoNaranja: { p: 6246, e: '🐦‍⬛', texts: ['¿Es de color negro pero su pico y los bordes de sus ojos son color naranja brillante (Mirlo)?', '¿Paseriforme negro que destaca por su pico marcadamente anaranjado?', '¿Túrdido de plumaje melánico que presenta anillo ocular y pico marcadamente amarillos o naranjas?'] },
    estorninoEstrellitas: { p: 6246, e: '🐦', texts: ['¿Es negro pero tiene manchitas blancas en las plumas como estrellitas (Estornino)?', '¿Ave negra cuyo plumaje está moteado de pequeños puntos claros?', '¿Paseriforme oscuro con plumaje iridiscente y un denso moteado claro estival?'] },
    nidoTejadoBaberoRojo: { p: 6246, e: '🐦', texts: ['¿Tiene la garganta o barbilla de color rojo oscuro y la cola con forma de horquilla (Golondrina)?', '¿Ave de pecho oscuro y cola muy ahorquillada que hace nidos de barro?', '¿Hirundínido de garganta rojiza, dorso oscuro azulado y rectrices externas muy elongadas?'] },
    culoBlancoVuelo: { p: 6246, e: '🐦', texts: ['¿Vuela muy rápido atrapando mosquitos y tiene la tripa blanca (Avión común)?', '¿Pequeña ave blanquinegra que tiene el vientre y obispillo de color blanco?', '¿Hirundínido de tamaño reducido, con obispillo y región ventral uniformemente blancos?'] },
    pechoLlamaRoja: { p: 6246, e: '🐦', texts: ['¿Es un pajarito pequeño y regordete con el pecho de color rojo o naranja fuerte (Petirrojo)?', '¿Pequeño pájaro rechoncho que destaca por tener un gran parche naranja en el pecho?', '¿Pequeño túrdido con una amplia e inconfundible placa de coloración rojizo-anaranjada en garganta y pecho?'] },
    franjaNegraPecho: { p: 6246, e: '🐦', texts: ['¿Tiene el vientre amarillo cruzado por una raya negra de arriba a abajo como una corbata (Carbonero)?', '¿Pájaro amarillo y verde con una línea vertical negra que le cruza el pecho?', '¿Párido de vientre amarillo atravesado verticalmente por una ancha banda melánica ("corbata")?'] },
    gorraAzulCabeza: { p: 6246, e: '🐦', texts: ['¿Es chiquitín, amarillo por debajo y tiene la parte de arriba de la cabeza de color azul vivo (Herrerillo)?', '¿Párido pequeño con plumaje facial blanco, pecho amarillo y píleo (gorra) azul brillante?', '¿Párido caracterizado por píleo y alas de color azul cerúleo y antifaz facial melánico estrecho?'] },
    rapazNocturna: { p: 6246, e: '🦉', texts: ['¿Es un pájaro cazador de ojos enormes mirando al frente que vuela sin hacer ruido por la noche (Búho o Lechuza)?', '¿Ave rapaz nocturna con grandes ojos frontales, cabeza redonda y vuelo muy silencioso?', '¿Estrigiforme de vuelo silente y disco facial bien desarrollado para visión nocturna?'] },
    caraBlancaFantasma: { p: 6246, e: '🦉', texts: ['¿Su cara es blanca en forma de corazón y de color muy pálido, pareciendo un fantasma (Lechuza)?', '¿Rapaz nocturna de plumaje muy claro con un disco facial blanco en forma de corazón?', '¿Estrigiforme pálido con disco facial cordiforme blanco, sin penachos cefálicos?'] },
    ciguenaCampanario: { p: 6246, e: '🦢', texts: ['¿Es un ave enorme, blanca y negra, con el pico largo rojo y grandes patas de zancuda (Cigüeña)?', '¿Gran ave zancuda blanca y negra de largo pico naranja o rojo?', '¿Ciconiforme de gran porte, plumaje pío, y pico y tarsos muy elongados de coloración rojiza?'] },
    rapazDiurnaV: { p: 6246, e: '🦅', texts: ['¿Es un ave cazadora enorme y marrón que vuela haciendo círculos agitando poco las alas (Milano/Águila)?', '¿Rapaz diurna grande que vuela cerniéndose, con alas largas y cola ahorquillada?', '¿Accipitriforme de gran envergadura alar, identificable por su cola ahorquillada en vuelo rasante?'] },

    // MAMÍFEROS
    ratonOjosGrandes: { p: 7281, e: '🐭', texts: ['¿Es un ratoncito marrón con los ojos y las orejas bastante grandes, que trepa bien (Ratón de campo)?', '¿Roedor pequeño silvestre de grandes ojos negros y orejas sobresalientes?', '¿Micromamífero múrido de pelaje pardo-rojizo con globos oculares y pabellones auriculares proporcionalmente grandes?'] },
    ratonCiegoTierra: { p: 7281, e: '🐹', texts: ['¿Parece un ratón "gordo y chato" con los ojos minúsculos escondidos, que vive bajo tierra (Topillo)?', '¿Roedor rechoncho de hocico achatado y orejas casi invisibles que excava galerías?', '¿Arvicólino de cuerpo cilíndrico, hocico romo, y orejas y ojos extremadamente reducidos?'] },
    pinchosEspalda: { p: 7281, e: '🦔', texts: ['¿Tiene pelillos duros convertidos en púas cortas por toda la espalda (Erizo)?', '¿Mamífero terrestre capaz de hacerse bola cubriendo su dorso con púas protectoras?', '¿Erinaceido cuyo dorso está densamente recubierto por púas queratinizadas erectiles?'] },
    orejasLargasMadriguera: { p: 7281, e: '🐰', texts: ['¿Tiene las orejas largas, cola de algodón y excava agujeros en la tierra (Conejo)?', '¿Mamífero saltador de orejas largas que vive en madrigueras subterráneas comunales?', '¿Lagomorfo de pabellones auriculares largos que excava complejas huras subterráneas?'] },
    orejasMuyLargasCorreCorto: { p: 7281, e: '🐇', texts: ['¿Sus orejas son larguísimas y sus patas traseras son enormes para correr a gran velocidad por campo abierto (Liebre)?', '¿Lagomorfo de enormes orejas y patas muy largas adaptado a la carrera rápida?', '¿Lagomorfo estepario de pabellones auriculares hipertrofiados y extremidades posteriores sumamente elongadas cursoriales?'] },
    colaGiganteZorro: { p: 7281, e: '🦊', texts: ['¿Es parecido a un perrito naranja o marrón con una cola muy grande y peluda (Zorro)?', '¿Cánido silvestre de hocico afilado, coloración rojiza y cola muy poblada de pelo?', '¿Cánido mediano de pelaje rubescente, hocico acuminado y apéndice caudal notablemente hirsuto?'] },
    pareceCiervoPequeno: { p: 7281, e: '🦌', texts: ['¿Parece un ciervo pequeño, elegante, y corre ágilmente por el bosque (Corzo)?', '¿Cérvido de pequeño tamaño cuyo macho tiene unas cuernas cortitas?', '¿Capreolino de pequeño porte, sin cola visible y escudo anal blanco destacado?'] },
    vuelaBocaAbajo: { p: 7281, e: '🦇', texts: ['¿Duerme colgando boca abajo y vuela de noche usando sus membranas oscuras (Murciélago)?', '¿Es el único mamífero capaz de volar, que descansa boca abajo en lugares oscuros?', '¿Quiróptero portador de patagio membranoso capaz de vuelo activo y hábitos lucífugos cavernícolas?'] },

    // LIZARDS & AMPHIBIANS
    pequenoParedSeltaCola: { p: 8666, e: '🦎', texts: ['¿Mide menos de una mano, trepa rápido por paredes y tiene rabo largo que se puede romper (Lagartija)?', '¿Reptil pequeño ágil que trepa muros y tiene facilidad para perder su cola?', '¿Pequeño lacértido trepador capaz de autotomía caudal como estrategia defensiva evasiva?'] },
    granDinosaurioVerde: { p: 8666, e: '🦎', texts: ['¿Es muy grande para ser lagartija (hasta 60 cm) y es de un verde fuerte con manchas redondas azules (Lagarto Ocelado)?', '¿Lagarto grande de fondo verde que tiene manchas azules oceladas en los costados?', '¿Lacértido de gran tamaño (supera 50cm) con librea verdosa jalonada de ocelos laterales azulados?'] },
    cuerpoHumedoSalta: { p: 8666, e: '🐸', texts: ['¿Tiene la piel lisa, mojada o húmeda, no tiene cola y da grandes saltos largos (Rana)?', '¿Anfibio liso, de piel escurridiza y extremidades traseras largas adaptadas al gran salto?', '¿Anuro de tegumento liso glandular mucoso, provisto de largas extremidades posteriores saltatorias?'] },
    pielVerrugosaCamina: { p: 8666, e: '🐸', texts: ['¿Tiene la piel seca con muchos bultitos como "verrugas", suele ser gordo y da pasitos cortos o saltos torpes (Sapo)?', '¿Anfibio terrestre robusto, de piel seca y rugosa (con pústulas) de movimientos lentos?', '¿Anuro robusto terrestre, de tegumento seco hiperqueratósico y pustuloso, de deambulación pesada?'] },

    // SNAKES (Tienen huesos = sÍ, 4 patas = NO)
    culebraDibujaEscalera: { p: 8666, e: '🐍', texts: ['¿Tiene rayas en la espalda que se cruzan y parecen peldaños de una escalera (Culebra de escalera)?', '¿Serpiente que tiene dibujadas franjas transversales en su dorso que simulan una escalera?', '¿Ofidio colúbrido cuyo patrón dorsal presenta líneas longitudinales y franjas transversas a modo de escala?'] },
    culebraLevantaSisea: { p: 8666, e: '🐍', texts: ['¿Es una serpiente lisa y alargada, a menudo marrón parda, sin dibujo de escalera (Culebra bastarda o similar)?', '¿Serpiente grande unicolor, bastante agresiva y que se asuela en los matorrales?', '¿Ofidio opistoglifo de gran porte, coloración isabelina y escamas supraoculares prominentes (mirada ceñuda)?'] }
};

const translations = {};
Object.keys(traitsMap).forEach(key => {
    let p = traitsMap[key].texts[0];
    let eText = traitsMap[key].texts[1] || p;
    let bText = traitsMap[key].texts[2] || eText;

    translations[key] = {
        text: { primaria: p, eso: eText, bachillerato: bText },
        pictoId: traitsMap[key].p,
        fallbackEmoji: traitsMap[key].e
    };
});

const tsOutput = `export type Category = "Planta" | "Invertebrado" | "Vertebrado";
export type TrophicLevel = "Productor" | "Consumidor Primario" | "Consumidor Secundario" | "Consumidor Terciario" | "Descomponedor";

export interface TraitMap {
    [key: string]: string | boolean | undefined;
}

export type Difficulty = "primaria" | "eso" | "bachillerato";

export interface Species {
    id: string;
    name: string;
    category: Category;
    trophicLevel: TrophicLevel;
    wikiQuery: string;
    imageUrl?: string;
    traits: TraitMap;
}

export const QUESTION_DEFS: Record<string, { text: { primaria: string; eso: string; bachillerato: string }; pictoId: number; fallbackEmoji: string }> = ${JSON.stringify(translations, null, 2)};
`;

fs.writeFileSync('C:\\\\Users\\\\VALIMANA\\\\Desktop\\\\Proyectos\\\\Tico.AI\\\\Juego_Ciencias_Milagros\\\\src\\\\data\\\\questions.ts', tsOutput);
console.log('Done questions script');
